### ISSUE TITLE
fetch from coastline

### ISSUE THREAD

**Issue by annacb** [blasee/fetchR#8]
Hello! I am trying to calculate fetch from the coastline of my spatial polygon, but because of the way this function is written, it counts the coastline as "on land" and will not calculate fetch. Is there a way to modify the code to get around this? Thanks

**Comment by blasee** [comment]
The `fetch()` function considers points on the coastline as being located on land. To get around this issue, you can simply shrink the polygon object using a small, negative value for the `width` argument in the `rgeos::gBuffer()` function. If you have multiple polygons, you will also want to use `byid = TRUE`, for example:

```{r}
my_shrunk_polygon = rgeos::gBuffer(my_polygon, width = -1, byid = TRUE)
```
